### ISSUE TITLE
Any CONTRIBUTING.md for this repo

### ISSUE THREAD

**Issue by onurctirtir** [nurulmac11/nurulmac11#1]
Do you plan to add a CONTRIBUTING.md file for this repo, thanks!

**Comment by nurulmac11** [comment]
Hello @onurctirtir,

Thank you so much for taking the time to engage with my personal bio repository and for your thoughtful suggestion regarding the addition of a CONTRIBUTING.md file. I truly value the community's interest and your willingness to contribute to enhancing this space.

The repository you've referenced serves as a personal biography and portfolio, primarily aimed at sharing my personal and professional journey, achievements, and projects. Given its nature as a personal narrative and showcase, the repository is structured in a way that reflects my individual experiences and milestones.

While I deeply appreciate the spirit of collaboration and community contribution, I've decided to maintain the repository without a CONTRIBUTING.md file. This decision stems from the repository's intent to serve as a personal narrative rather than a collaborative project. The content is a reflection of my personal journey and perspectives, and as such, it is curated and updated based on my individual experiences and achievements.

However, I want to emphasize how much I value community feedback and engagement. Your interaction is a reminder of the vibrant and supportive community we are part of. While this specific repository may not be the right platform for collaborative contributions, I am always eager to engage in discussions, share insights, and collaborate on other projects or platforms that encourage community participation.

Please feel free to connect with me through other channels or repositories that are designed for collaboration. Your insights, feedback, and contributions are invaluable to fostering a dynamic and inclusive community.

Thank you once again for your understanding and your proactive approach to community engagement. I look forward to any future interactions and appreciate your support and interest in my work.

Best regards,
nurulmac11

**Comment by onurctirtir** [comment]
Heavily smells like a ChatGPT text but thanks @nurulmac11!
